[project]
name = "career-mentor-agent"
version = "0.0.2"
description = "some changes "
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai-agents>=0.2.5",
    "python-dotenv>=1.1.1",
]
